EngineUserSettings {
 AudioSettings AudioSettings {
 }
 DisplayUserSettings DisplayUserSettings {
  PPQuality PPEffectsSettings "{6A7AE2D8015CB6DC}" {
  }
 }
 GameProjectUserSettings GameProjectUserSettings {
 }
 GraphicsQualitySettings GraphicsQualitySettings {
 }
 GrassMaterialSettings GrassMaterialSettings {
 }
 InputDeviceUserSettings InputDeviceUserSettings {
  GamepadProfile InputProfileGamepad "{6A7AE2D80477146F}" {
   LeftThumbHorizontal InputProfileKey "{6A7AE2D804771475}" {
    Transition CurveCubicSplineFloat "{6A7AE2D804771471}" {
    }
   }
   LeftThumbVertical InputProfileKey "{6A7AE2D80477147C}" {
    Transition CurveCubicSplineFloat "{6A7AE2D80477147E}" {
    }
   }
   RightThumbHorizontal InputProfileKey "{6A7AE2D804771445}" {
    Transition CurveCubicSplineFloat "{6A7AE2D804771447}" {
    }
   }
   RightThumbVertical InputProfileKey "{6A7AE2D804771441}" {
    Transition CurveCubicSplineFloat "{6A7AE2D804771440}" {
    }
   }
   LeftTrigger InputProfileKey "{6A7AE2D80477144D}" {
    Transition CurveCubicSplineFloat "{6A7AE2D80477145D}" {
    }
   }
   RightTrigger InputProfileKey "{6A7AE2D80477145E}" {
    Transition CurveCubicSplineFloat "{6A7AE2D804771458}" {
    }
   }
  }
  JoystickProfile InputProfileJoystick "{6A7AE2D80477145A}" {
   Axis00 InputProfileKey "{6A7AE2D8047715A4}" {
    Transition CurveCubicSplineFloat "{6A7AE2D8047715A0}" {
    }
   }
   Axis01 InputProfileKey "{6A7AE2D8047715AD}" {
    Transition CurveCubicSplineFloat "{6A7AE2D8047715AF}" {
    }
   }
   Axis02 InputProfileKey "{6A7AE2D8047715A8}" {
    Transition CurveCubicSplineFloat "{6A7AE2D8047715AA}" {
    }
   }
   Axis03 InputProfileKey "{6A7AE2D8047715B4}" {
    Transition CurveCubicSplineFloat "{6A7AE2D8047715B6}" {
    }
   }
   Axis04 InputProfileKey "{6A7AE2D8047715B0}" {
    Transition CurveCubicSplineFloat "{6A7AE2D8047715B2}" {
    }
   }
   Axis05 InputProfileKey "{6A7AE2D8047715BD}" {
    Transition CurveCubicSplineFloat "{6A7AE2D8047715BF}" {
    }
   }
   Axis06 InputProfileKey "{6A7AE2D8047715BE}" {
    Transition CurveCubicSplineFloat "{6A7AE2D8047715B8}" {
    }
   }
   Axis07 InputProfileKey "{6A7AE2D8047715BB}" {
    Transition CurveCubicSplineFloat "{6A7AE2D804771C7E}" {
    }
   }
   Axis08 InputProfileKey "{6A7AE2D804771C40}" {
    Transition CurveCubicSplineFloat "{6A7AE2D804771C41}" {
    }
   }
   Axis09 InputProfileKey "{6A7AE2D804771C42}" {
    Transition CurveCubicSplineFloat "{6A7AE2D804771C44}" {
    }
   }
  }
  JoystickSettings JoystickSettings "{6A7AE2D804771C48}" {
  }
  GyroSettings GyroSettings "{6A7AE2D804771C4F}" {
  }
 }
 MaterialSystemUserSettings MaterialSystemUserSettings {
 }
 PipelineUserSettings PipelineUserSettings {
 }
 PostprocessUserSettings PostprocessUserSettings {
 }
 ResourceManagerUserSettings ResourceManagerUserSettings {
 }
 TerrainGenMaterialSettings TerrainGenMaterialSettings {
 }
 UserInterfaceSettings UserInterfaceSettings {
  LanguageCode "en_us"
  SystemLanguageCode "en_us"
 }
 VideoUserSettings VideoUserSettings {
  WindowMode WINDOWED
  ScreenWidth 1920
  ScreenHeight 1080
  ResolutionScale 1
  WindowPosX 0
  WindowPosY 31
  Vsync 1
  Ratio3d 1
  Fsaa NONE
  RenderFormat STANDARD
  Gamma 0
  Contrast 0
  Brightness 0
  FsrEnabled 0
  FsrSharpening 0.75
  CasSharpening 0
 }
 WaterPoolMaterialSettings WaterPoolMaterialSettings {
 }
}