GameUserSettings {
 GameplaySettings GameplaySettings {
 }
 SCR_HeadTrackingSettings SCR_HeadTrackingSettings {
 }
 SCR_InventoryHintSettings SCR_InventoryHintSettings {
 }
 SCR_EditorPersistentData SCR_EditorPersistentData {
 }
 SCR_ControllerSettings SCR_ControllerSettings {
 }
 SCR_EditorSettings SCR_EditorSettings {
 }
 SCR_GameplaySettings SCR_GameplaySettings {
 }
 SCR_FieldOfViewSettings SCR_FieldOfViewSettings {
 }
 SCR_HintSettings SCR_HintSettings {
  m_aShownHints {
   EDITOR_MODE_EDIT
  }
  m_aShownHintCounts {
   1
  }
 }
 SCR_VideoSettings SCR_VideoSettings {
 }
 SCR_AudioSettings SCR_AudioSettings {
 }
 SCR_AimSensitivitySettings SCR_AimSensitivitySettings {
 }
 SCR_InterfaceSettings SCR_InterfaceSettings {
 }
 SCR_ManualCameraSettings SCR_ManualCameraSettings {
 }
}