EngineUserSettings {
 AudioSettings AudioSettings {
 }
 DisplayUserSettings DisplayUserSettings {
  PPQuality PPEffectsSettings "{6A7AE29801C904D9}" {
  }
 }
 GameProjectUserSettings GameProjectUserSettings {
 }
 GraphicsQualitySettings GraphicsQualitySettings {
 }
 GrassMaterialSettings GrassMaterialSettings {
 }
 InputDeviceUserSettings InputDeviceUserSettings {
  GamepadProfile InputProfileGamepad "{6A7AE2980477F014}" {
   LeftThumbHorizontal InputProfileKey "{6A7AE2980477F01C}" {
    Transition CurveCubicSplineFloat "{6A7AE2980477F065}" {
    }
   }
   LeftThumbVertical InputProfileKey "{6A7AE2980477F060}" {
    Transition CurveCubicSplineFloat "{6A7AE2980477F06D}" {
    }
   }
   RightThumbHorizontal InputProfileKey "{6A7AE2980477F06F}" {
    Transition CurveCubicSplineFloat "{6A7AE2980477F06E}" {
    }
   }
   RightThumbVertical InputProfileKey "{6A7AE2980477F06B}" {
    Transition CurveCubicSplineFloat "{6A7AE2980477F06A}" {
    }
   }
   LeftTrigger InputProfileKey "{6A7AE2980477F074}" {
    Transition CurveCubicSplineFloat "{6A7AE2980477F046}" {
    }
   }
   RightTrigger InputProfileKey "{6A7AE2980477F040}" {
    Transition CurveCubicSplineFloat "{6A7AE2980477F042}" {
    }
   }
  }
  JoystickProfile InputProfileJoystick "{6A7AE2980477F04E}" {
   Axis00 InputProfileKey "{6A7AE2980477F04B}" {
    Transition CurveCubicSplineFloat "{6A7AE2980477F054}" {
    }
   }
   Axis01 InputProfileKey "{6A7AE2980477F056}" {
    Transition CurveCubicSplineFloat "{6A7AE2980477F053}" {
    }
   }
   Axis02 InputProfileKey "{6A7AE2980477F05C}" {
    Transition CurveCubicSplineFloat "{6A7AE2980477F05E}" {
    }
   }
   Axis03 InputProfileKey "{6A7AE2980477F058}" {
    Transition CurveCubicSplineFloat "{6A7AE2980477F05A}" {
    }
   }
   Axis04 InputProfileKey "{6A7AE2980477F1A4}" {
    Transition CurveCubicSplineFloat "{6A7AE2980477F1A6}" {
    }
   }
   Axis05 InputProfileKey "{6A7AE2980477F1A1}" {
    Transition CurveCubicSplineFloat "{6A7AE2980477F1A3}" {
    }
   }
   Axis06 InputProfileKey "{6A7AE2980477F1AD}" {
    Transition CurveCubicSplineFloat "{6A7AE2980477F1AC}" {
    }
   }
   Axis07 InputProfileKey "{6A7AE2980477F1AF}" {
    Transition CurveCubicSplineFloat "{6A7AE2980477F1AE}" {
    }
   }
   Axis08 InputProfileKey "{6A7AE2980477F1A8}" {
    Transition CurveCubicSplineFloat "{6A7AE2980477F1AB}" {
    }
   }
   Axis09 InputProfileKey "{6A7AE2980477F1B5}" {
    Transition CurveCubicSplineFloat "{6A7AE2980477F1B4}" {
    }
   }
  }
  JoystickSettings JoystickSettings "{6A7AE2980477F1B3}" {
  }
  GyroSettings GyroSettings "{6A7AE2980477F1B9}" {
  }
 }
 MaterialSystemUserSettings MaterialSystemUserSettings {
 }
 PipelineUserSettings PipelineUserSettings {
 }
 PostprocessUserSettings PostprocessUserSettings {
 }
 ResourceManagerUserSettings ResourceManagerUserSettings {
 }
 TerrainGenMaterialSettings TerrainGenMaterialSettings {
 }
 UserInterfaceSettings UserInterfaceSettings {
  LanguageCode "en_us"
  SystemLanguageCode "en_us"
 }
 VideoUserSettings VideoUserSettings {
  WindowMode WINDOWED
  ScreenWidth 1920
  ScreenHeight 1080
  ResolutionScale 1
  WindowPosX 0
  WindowPosY 31
  Vsync 1
  Ratio3d 1
  Fsaa NONE
  RenderFormat STANDARD
  Gamma 0
  Contrast 0
  Brightness 0
  FsrEnabled 0
  FsrSharpening 0.75
  CasSharpening 0
 }
 WaterPoolMaterialSettings WaterPoolMaterialSettings {
 }
}