EngineUserSettings {
 AudioSettings AudioSettings {
 }
 DisplayUserSettings DisplayUserSettings {
  PPQuality PPEffectsSettings "{6A7ADACD00BBF022}" {
  }
 }
 GameProjectUserSettings GameProjectUserSettings {
 }
 GraphicsQualitySettings GraphicsQualitySettings {
 }
 GrassMaterialSettings GrassMaterialSettings {
 }
 InputDeviceUserSettings InputDeviceUserSettings {
  GamepadProfile InputProfileGamepad "{6A7ADACD0463BC39}" {
   LeftThumbHorizontal InputProfileKey "{6A7ADACD0463BC06}" {
    Transition CurveCubicSplineFloat "{6A7ADACD0463BC0C}" {
    }
   }
   LeftThumbVertical InputProfileKey "{6A7ADACD0463BC14}" {
    Transition CurveCubicSplineFloat "{6A7ADACD0463BC11}" {
    }
   }
   RightThumbHorizontal InputProfileKey "{6A7ADACD0463BC10}" {
    Transition CurveCubicSplineFloat "{6A7ADACD0463BC12}" {
    }
   }
   RightThumbVertical InputProfileKey "{6A7ADACD0463BC1F}" {
    Transition CurveCubicSplineFloat "{6A7ADACD0463BC19}" {
    }
   }
   LeftTrigger InputProfileKey "{6A7ADACD0463BC1B}" {
    Transition CurveCubicSplineFloat "{6A7ADACD0463BC76}" {
    }
   }
   RightTrigger InputProfileKey "{6A7ADACD0463BC70}" {
    Transition CurveCubicSplineFloat "{6A7ADACD0463BC72}" {
    }
   }
  }
  JoystickProfile InputProfileJoystick "{6A7ADACD0463BC7F}" {
   Axis00 InputProfileKey "{6A7ADACD0463BC78}" {
    Transition CurveCubicSplineFloat "{6A7ADACD0463BC44}" {
    }
   }
   Axis01 InputProfileKey "{6A7ADACD0463BC46}" {
    Transition CurveCubicSplineFloat "{6A7ADACD0463BC40}" {
    }
   }
   Axis02 InputProfileKey "{6A7ADACD0463BC42}" {
    Transition CurveCubicSplineFloat "{6A7ADACD0463BC4C}" {
    }
   }
   Axis03 InputProfileKey "{6A7ADACD0463BC49}" {
    Transition CurveCubicSplineFloat "{6A7ADACD0463BC48}" {
    }
   }
   Axis04 InputProfileKey "{6A7ADACD0463BC4A}" {
    Transition CurveCubicSplineFloat "{6A7ADACD0463BC54}" {
    }
   }
   Axis05 InputProfileKey "{6A7ADACD0463BC57}" {
    Transition CurveCubicSplineFloat "{6A7ADACD0463BC51}" {
    }
   }
   Axis06 InputProfileKey "{6A7ADACD0463BC53}" {
    Transition CurveCubicSplineFloat "{6A7ADACD0463BC52}" {
    }
   }
   Axis07 InputProfileKey "{6A7ADACD0463BC5D}" {
    Transition CurveCubicSplineFloat "{6A7ADACD0463BC5C}" {
    }
   }
   Axis08 InputProfileKey "{6A7ADACD0463BC5E}" {
    Transition CurveCubicSplineFloat "{6A7ADACD0463BC59}" {
    }
   }
   Axis09 InputProfileKey "{6A7ADACD0463BC5B}" {
    Transition CurveCubicSplineFloat "{6A7ADACD0463BC5A}" {
    }
   }
  }
  JoystickSettings JoystickSettings "{6A7ADACD0463BDA6}" {
  }
  GyroSettings GyroSettings "{6A7ADACD0463BDAF}" {
  }
 }
 MaterialSystemUserSettings MaterialSystemUserSettings {
 }
 PipelineUserSettings PipelineUserSettings {
 }
 PostprocessUserSettings PostprocessUserSettings {
 }
 ResourceManagerUserSettings ResourceManagerUserSettings {
 }
 TerrainGenMaterialSettings TerrainGenMaterialSettings {
 }
 UserInterfaceSettings UserInterfaceSettings {
  LanguageCode "en_us"
  SystemLanguageCode "en_us"
 }
 VideoUserSettings VideoUserSettings {
  WindowMode WINDOWED
  ScreenWidth 1920
  ScreenHeight 1080
  ResolutionScale 1
  WindowPosX 0
  WindowPosY 31
  Vsync 1
  Ratio3d 1
  Fsaa NONE
  RenderFormat STANDARD
  Gamma 0
  Contrast 0
  Brightness 0
  FsrEnabled 0
  FsrSharpening 0.75
  CasSharpening 0
 }
 WaterPoolMaterialSettings WaterPoolMaterialSettings {
 }
}