EngineUserSettings {
 AudioSettings AudioSettings {
 }
 DisplayUserSettings DisplayUserSettings {
  PPQuality PPEffectsSettings "{6A7AE19201C25A8C}" {
  }
 }
 GameProjectUserSettings GameProjectUserSettings {
 }
 GraphicsQualitySettings GraphicsQualitySettings {
 }
 GrassMaterialSettings GrassMaterialSettings {
 }
 InputDeviceUserSettings InputDeviceUserSettings {
  GamepadProfile InputProfileGamepad "{6A7AE192047881C9}" {
   LeftThumbHorizontal InputProfileKey "{6A7AE192047881D7}" {
    Transition CurveCubicSplineFloat "{6A7AE192047881D2}" {
    }
   }
   LeftThumbVertical InputProfileKey "{6A7AE192047881DA}" {
    Transition CurveCubicSplineFloat "{6A7AE19204788127}" {
    }
   }
   RightThumbHorizontal InputProfileKey "{6A7AE19204788120}" {
    Transition CurveCubicSplineFloat "{6A7AE19204788122}" {
    }
   }
   RightThumbVertical InputProfileKey "{6A7AE1920478812D}" {
    Transition CurveCubicSplineFloat "{6A7AE1920478812C}" {
    }
   }
   LeftTrigger InputProfileKey "{6A7AE1920478812F}" {
    Transition CurveCubicSplineFloat "{6A7AE1920478813F}" {
    }
   }
   RightTrigger InputProfileKey "{6A7AE19204788139}" {
    Transition CurveCubicSplineFloat "{6A7AE1920478813B}" {
    }
   }
  }
  JoystickProfile InputProfileJoystick "{6A7AE19204788105}" {
   Axis00 InputProfileKey "{6A7AE19204788101}" {
    Transition CurveCubicSplineFloat "{6A7AE19204788102}" {
    }
   }
   Axis01 InputProfileKey "{6A7AE1920478810F}" {
    Transition CurveCubicSplineFloat "{6A7AE19204788109}" {
    }
   }
   Axis02 InputProfileKey "{6A7AE1920478810B}" {
    Transition CurveCubicSplineFloat "{6A7AE19204788115}" {
    }
   }
   Axis03 InputProfileKey "{6A7AE19204788114}" {
    Transition CurveCubicSplineFloat "{6A7AE19204788116}" {
    }
   }
   Axis04 InputProfileKey "{6A7AE19204788111}" {
    Transition CurveCubicSplineFloat "{6A7AE19204788113}" {
    }
   }
   Axis05 InputProfileKey "{6A7AE1920478811D}" {
    Transition CurveCubicSplineFloat "{6A7AE1920478811F}" {
    }
   }
   Axis06 InputProfileKey "{6A7AE1920478811E}" {
    Transition CurveCubicSplineFloat "{6A7AE19204788119}" {
    }
   }
   Axis07 InputProfileKey "{6A7AE19204788118}" {
    Transition CurveCubicSplineFloat "{6A7AE192047888DD}" {
    }
   }
   Axis08 InputProfileKey "{6A7AE192047888DF}" {
    Transition CurveCubicSplineFloat "{6A7AE19204787A15}" {
    }
   }
   Axis09 InputProfileKey "{6A7AE19204787A6A}" {
    Transition CurveCubicSplineFloat "{6A7AE19204787A68}" {
    }
   }
  }
  JoystickSettings JoystickSettings "{6A7AE19204787A6E}" {
  }
  GyroSettings GyroSettings "{6A7AE19204787A63}" {
  }
 }
 MaterialSystemUserSettings MaterialSystemUserSettings {
 }
 PipelineUserSettings PipelineUserSettings {
 }
 PostprocessUserSettings PostprocessUserSettings {
 }
 ResourceManagerUserSettings ResourceManagerUserSettings {
 }
 TerrainGenMaterialSettings TerrainGenMaterialSettings {
 }
 UserInterfaceSettings UserInterfaceSettings {
  LanguageCode "en_us"
  SystemLanguageCode "en_us"
 }
 VideoUserSettings VideoUserSettings {
  WindowPosX 0
  WindowPosY -60
 }
 WaterPoolMaterialSettings WaterPoolMaterialSettings {
 }
}