EngineUserSettings {
 AudioSettings AudioSettings {
 }
 DisplayUserSettings DisplayUserSettings {
  PPQuality PPEffectsSettings "{6A7AE0F00192B059}" {
  }
 }
 GameProjectUserSettings GameProjectUserSettings {
 }
 GraphicsQualitySettings GraphicsQualitySettings {
 }
 GrassMaterialSettings GrassMaterialSettings {
 }
 InputDeviceUserSettings InputDeviceUserSettings {
  GamepadProfile InputProfileGamepad "{6A7AE0F00473B719}" {
   LeftThumbHorizontal InputProfileKey "{6A7AE0F00473B766}" {
    Transition CurveCubicSplineFloat "{6A7AE0F00473B76D}" {
    }
   }
   LeftThumbVertical InputProfileKey "{6A7AE0F00473B76B}" {
    Transition CurveCubicSplineFloat "{6A7AE0F00473B76A}" {
    }
   }
   RightThumbHorizontal InputProfileKey "{6A7AE0F00473B777}" {
    Transition CurveCubicSplineFloat "{6A7AE0F00473B771}" {
    }
   }
   RightThumbVertical InputProfileKey "{6A7AE0F00473B770}" {
    Transition CurveCubicSplineFloat "{6A7AE0F00473B772}" {
    }
   }
   LeftTrigger InputProfileKey "{6A7AE0F00473BEB7}" {
    Transition CurveCubicSplineFloat "{6A7AE0F00473BE86}" {
    }
   }
   RightTrigger InputProfileKey "{6A7AE0F00473BE88}" {
    Transition CurveCubicSplineFloat "{6A7AE0F00473BE8B}" {
    }
   }
  }
  JoystickProfile InputProfileJoystick "{6A7AE0F00473BE8E}" {
   Axis00 InputProfileKey "{6A7AE0F00473BE90}" {
    Transition CurveCubicSplineFloat "{6A7AE0F00473BE94}" {
    }
   }
   Axis01 InputProfileKey "{6A7AE0F00473BE96}" {
    Transition CurveCubicSplineFloat "{6A7AE0F00473BE98}" {
    }
   }
   Axis02 InputProfileKey "{6A7AE0F00473BE9B}" {
    Transition CurveCubicSplineFloat "{6A7AE0F00473BE9C}" {
    }
   }
   Axis03 InputProfileKey "{6A7AE0F00473BE9E}" {
    Transition CurveCubicSplineFloat "{6A7AE0F00473BD60}" {
    }
   }
   Axis04 InputProfileKey "{6A7AE0F00473BD62}" {
    Transition CurveCubicSplineFloat "{6A7AE0F00473BD64}" {
    }
   }
   Axis05 InputProfileKey "{6A7AE0F00473BD66}" {
    Transition CurveCubicSplineFloat "{6A7AE0F00473BD67}" {
    }
   }
   Axis06 InputProfileKey "{6A7AE0F00473BD69}" {
    Transition CurveCubicSplineFloat "{6A7AE0F00473BD6A}" {
    }
   }
   Axis07 InputProfileKey "{6A7AE0F00473BD6B}" {
    Transition CurveCubicSplineFloat "{6A7AE0F00473BD6D}" {
    }
   }
   Axis08 InputProfileKey "{6A7AE0F00473BD6E}" {
    Transition CurveCubicSplineFloat "{6A7AE0F00473BD6F}" {
    }
   }
   Axis09 InputProfileKey "{6A7AE0F00473BD70}" {
    Transition CurveCubicSplineFloat "{6A7AE0F00473BD71}" {
    }
   }
  }
  JoystickSettings JoystickSettings "{6A7AE0F00473BD74}" {
  }
  GyroSettings GyroSettings "{6A7AE0F00473BD78}" {
  }
 }
 MaterialSystemUserSettings MaterialSystemUserSettings {
 }
 PipelineUserSettings PipelineUserSettings {
 }
 PostprocessUserSettings PostprocessUserSettings {
 }
 ResourceManagerUserSettings ResourceManagerUserSettings {
 }
 TerrainGenMaterialSettings TerrainGenMaterialSettings {
 }
 UserInterfaceSettings UserInterfaceSettings {
  LanguageCode "en_us"
  SystemLanguageCode "en_us"
 }
 VideoUserSettings VideoUserSettings {
  WindowMode WINDOWED
  ScreenWidth 1920
  ScreenHeight 1080
  ResolutionScale 1
  WindowPosX 0
  WindowPosY 31
  Vsync 1
  Ratio3d 1
  Fsaa NONE
  RenderFormat STANDARD
  Gamma 0
  Contrast 0
  Brightness 0
  FsrEnabled 0
  FsrSharpening 0.75
  CasSharpening 0
 }
 WaterPoolMaterialSettings WaterPoolMaterialSettings {
 }
}