EngineUserSettings {
 AudioSettings AudioSettings {
 }
 DisplayUserSettings DisplayUserSettings {
  PPQuality PPEffectsSettings "{6A7ADEF802E44240}" {
  }
 }
 GameProjectUserSettings GameProjectUserSettings {
 }
 GraphicsQualitySettings GraphicsQualitySettings {
 }
 GrassMaterialSettings GrassMaterialSettings {
 }
 InputDeviceUserSettings InputDeviceUserSettings {
  GamepadProfile InputProfileGamepad "{6A7ADEF80470C9BC}" {
   LeftThumbHorizontal InputProfileKey "{6A7ADEF80470C985}" {
    Transition CurveCubicSplineFloat "{6A7ADEF80470C981}" {
    }
   }
   LeftThumbVertical InputProfileKey "{6A7ADEF80470C98E}" {
    Transition CurveCubicSplineFloat "{6A7ADEF80470C988}" {
    }
   }
   RightThumbHorizontal InputProfileKey "{6A7ADEF80470C98A}" {
    Transition CurveCubicSplineFloat "{6A7ADEF80470C995}" {
    }
   }
   RightThumbVertical InputProfileKey "{6A7ADEF80470C996}" {
    Transition CurveCubicSplineFloat "{6A7ADEF80470C991}" {
    }
   }
   LeftTrigger InputProfileKey "{6A7ADEF80470C993}" {
    Transition CurveCubicSplineFloat "{6A7ADEF80470C9E1}" {
    }
   }
   RightTrigger InputProfileKey "{6A7ADEF80470C9E2}" {
    Transition CurveCubicSplineFloat "{6A7ADEF80470C9ED}" {
    }
   }
  }
  JoystickProfile InputProfileJoystick "{6A7ADEF80470C9E9}" {
   Axis00 InputProfileKey "{6A7ADEF80470C9EA}" {
    Transition CurveCubicSplineFloat "{6A7ADEF80470C9F7}" {
    }
   }
   Axis01 InputProfileKey "{6A7ADEF80470C9F1}" {
    Transition CurveCubicSplineFloat "{6A7ADEF80470C9F3}" {
    }
   }
   Axis02 InputProfileKey "{6A7ADEF80470C9FD}" {
    Transition CurveCubicSplineFloat "{6A7ADEF80470C9FC}" {
    }
   }
   Axis03 InputProfileKey "{6A7ADEF80470C9FE}" {
    Transition CurveCubicSplineFloat "{6A7ADEF80470C9F8}" {
    }
   }
   Axis04 InputProfileKey "{6A7ADEF80470C9FA}" {
    Transition CurveCubicSplineFloat "{6A7ADEF80470C9C4}" {
    }
   }
   Axis05 InputProfileKey "{6A7ADEF80470C9C6}" {
    Transition CurveCubicSplineFloat "{6A7ADEF80470C9C0}" {
    }
   }
   Axis06 InputProfileKey "{6A7ADEF80470C9C3}" {
    Transition CurveCubicSplineFloat "{6A7ADEF80470C9C2}" {
    }
   }
   Axis07 InputProfileKey "{6A7ADEF80470C9CD}" {
    Transition CurveCubicSplineFloat "{6A7ADEF80470C9CF}" {
    }
   }
   Axis08 InputProfileKey "{6A7ADEF80470C9CE}" {
    Transition CurveCubicSplineFloat "{6A7ADEF80470C9C8}" {
    }
   }
   Axis09 InputProfileKey "{6A7ADEF80470C9CB}" {
    Transition CurveCubicSplineFloat "{6A7ADEF80470C9CA}" {
    }
   }
  }
  JoystickSettings JoystickSettings "{6A7ADEF80470C9D7}" {
  }
  GyroSettings GyroSettings "{6A7ADEF80470C9D2}" {
  }
 }
 MaterialSystemUserSettings MaterialSystemUserSettings {
 }
 PipelineUserSettings PipelineUserSettings {
 }
 PostprocessUserSettings PostprocessUserSettings {
 }
 ResourceManagerUserSettings ResourceManagerUserSettings {
 }
 TerrainGenMaterialSettings TerrainGenMaterialSettings {
 }
 UserInterfaceSettings UserInterfaceSettings {
  LanguageCode "en_us"
  SystemLanguageCode "en_us"
 }
 VideoUserSettings VideoUserSettings {
  WindowPosX -960
  WindowPosY -540
 }
 WaterPoolMaterialSettings WaterPoolMaterialSettings {
 }
}