EngineUserSettings {
 AudioSettings AudioSettings {
 }
 DisplayUserSettings DisplayUserSettings {
  PPQuality PPEffectsSettings "{6A7ADDFA009D3A37}" {
  }
 }
 GameProjectUserSettings GameProjectUserSettings {
 }
 GraphicsQualitySettings GraphicsQualitySettings {
 }
 GrassMaterialSettings GrassMaterialSettings {
 }
 InputDeviceUserSettings InputDeviceUserSettings {
  GamepadProfile InputProfileGamepad "{6A7ADDFA04727DD4}" {
   LeftThumbHorizontal InputProfileKey "{6A7ADDFA04727DDC}" {
    Transition CurveCubicSplineFloat "{6A7ADDFA04727DDB}" {
    }
   }
   LeftThumbVertical InputProfileKey "{6A7ADDFA04727D26}" {
    Transition CurveCubicSplineFloat "{6A7ADDFA04727D20}" {
    }
   }
   RightThumbHorizontal InputProfileKey "{6A7ADDFA04727D22}" {
    Transition CurveCubicSplineFloat "{6A7ADDFA04727D2C}" {
    }
   }
   RightThumbVertical InputProfileKey "{6A7ADDFA04727D2F}" {
    Transition CurveCubicSplineFloat "{6A7ADDFA04727D2E}" {
    }
   }
   LeftTrigger InputProfileKey "{6A7ADDFA04727D29}" {
    Transition CurveCubicSplineFloat "{6A7ADDFA04727D38}" {
    }
   }
   RightTrigger InputProfileKey "{6A7ADDFA04727D3A}" {
    Transition CurveCubicSplineFloat "{6A7ADDFA04727D07}" {
    }
   }
  }
  JoystickProfile InputProfileJoystick "{6A7ADDFA04727D00}" {
   Axis00 InputProfileKey "{6A7ADDFA04727D0D}" {
    Transition CurveCubicSplineFloat "{6A7ADDFA04727D09}" {
    }
   }
   Axis01 InputProfileKey "{6A7ADDFA04727D0B}" {
    Transition CurveCubicSplineFloat "{6A7ADDFA04727D15}" {
    }
   }
   Axis02 InputProfileKey "{6A7ADDFA04727D17}" {
    Transition CurveCubicSplineFloat "{6A7ADDFA04727D11}" {
    }
   }
   Axis03 InputProfileKey "{6A7ADDFA04727D13}" {
    Transition CurveCubicSplineFloat "{6A7ADDFA04727D1D}" {
    }
   }
   Axis04 InputProfileKey "{6A7ADDFA04727D1F}" {
    Transition CurveCubicSplineFloat "{6A7ADDFA04727D19}" {
    }
   }
   Axis05 InputProfileKey "{6A7ADDFA04727D18}" {
    Transition CurveCubicSplineFloat "{6A7ADDFA04727D1A}" {
    }
   }
   Axis06 InputProfileKey "{6A7ADDFA04727D64}" {
    Transition CurveCubicSplineFloat "{6A7ADDFA04727D67}" {
    }
   }
   Axis07 InputProfileKey "{6A7ADDFA04727D66}" {
    Transition CurveCubicSplineFloat "{6A7ADDFA04727D61}" {
    }
   }
   Axis08 InputProfileKey "{6A7ADDFA04727D60}" {
    Transition CurveCubicSplineFloat "{6A7ADDFA04727D63}" {
    }
   }
   Axis09 InputProfileKey "{6A7ADDFA04727D62}" {
    Transition CurveCubicSplineFloat "{6A7ADDFA047274A7}" {
    }
   }
  }
  JoystickSettings JoystickSettings "{6A7ADDFA047274AB}" {
  }
  GyroSettings GyroSettings "{6A7ADDFA047274B0}" {
  }
 }
 MaterialSystemUserSettings MaterialSystemUserSettings {
 }
 PipelineUserSettings PipelineUserSettings {
 }
 PostprocessUserSettings PostprocessUserSettings {
 }
 ResourceManagerUserSettings ResourceManagerUserSettings {
 }
 TerrainGenMaterialSettings TerrainGenMaterialSettings {
 }
 UserInterfaceSettings UserInterfaceSettings {
  LanguageCode "en_us"
  SystemLanguageCode "en_us"
 }
 VideoUserSettings VideoUserSettings {
  WindowPosX 320
  WindowPosY 180
 }
 WaterPoolMaterialSettings WaterPoolMaterialSettings {
 }
}