EngineUserSettings {
 AudioSettings AudioSettings {
 }
 DisplayUserSettings DisplayUserSettings {
  PPQuality PPEffectsSettings "{6A7AE2570051D460}" {
  }
 }
 GameProjectUserSettings GameProjectUserSettings {
 }
 GraphicsQualitySettings GraphicsQualitySettings {
 }
 GrassMaterialSettings GrassMaterialSettings {
 }
 InputDeviceUserSettings InputDeviceUserSettings {
  GamepadProfile InputProfileGamepad "{6A7AE25704798D46}" {
   LeftThumbHorizontal InputProfileKey "{6A7AE25704798D4F}" {
    Transition CurveCubicSplineFloat "{6A7AE25704798D55}" {
    }
   }
   LeftThumbVertical InputProfileKey "{6A7AE25704798D50}" {
    Transition CurveCubicSplineFloat "{6A7AE25704798D52}" {
    }
   }
   RightThumbHorizontal InputProfileKey "{6A7AE25704798D5C}" {
    Transition CurveCubicSplineFloat "{6A7AE25704798D5E}" {
    }
   }
   RightThumbVertical InputProfileKey "{6A7AE25704798D58}" {
    Transition CurveCubicSplineFloat "{6A7AE25704798D5B}" {
    }
   }
   LeftTrigger InputProfileKey "{6A7AE25704798AA5}" {
    Transition CurveCubicSplineFloat "{6A7AE25704798AAA}" {
    }
   }
   RightTrigger InputProfileKey "{6A7AE25704798AB4}" {
    Transition CurveCubicSplineFloat "{6A7AE25704798AB6}" {
    }
   }
  }
  JoystickProfile InputProfileJoystick "{6A7AE25704798AB2}" {
   Axis00 InputProfileKey "{6A7AE25704798ABC}" {
    Transition CurveCubicSplineFloat "{6A7AE25704798AB8}" {
    }
   }
   Axis01 InputProfileKey "{6A7AE25704798ABA}" {
    Transition CurveCubicSplineFloat "{6A7AE25704798A84}" {
    }
   }
   Axis02 InputProfileKey "{6A7AE25704798A87}" {
    Transition CurveCubicSplineFloat "{6A7AE25704798A8C}" {
    }
   }
   Axis03 InputProfileKey "{6A7AE25704798A8E}" {
    Transition CurveCubicSplineFloat "{6A7AE25704798A95}" {
    }
   }
   Axis04 InputProfileKey "{6A7AE25704798A97}" {
    Transition CurveCubicSplineFloat "{6A7AE25704798A91}" {
    }
   }
   Axis05 InputProfileKey "{6A7AE25704798A90}" {
    Transition CurveCubicSplineFloat "{6A7AE25704798A93}" {
    }
   }
   Axis06 InputProfileKey "{6A7AE25704798A9D}" {
    Transition CurveCubicSplineFloat "{6A7AE25704798A9F}" {
    }
   }
   Axis07 InputProfileKey "{6A7AE25704798A99}" {
    Transition CurveCubicSplineFloat "{6A7AE25704798A9B}" {
    }
   }
   Axis08 InputProfileKey "{6A7AE25704798AE5}" {
    Transition CurveCubicSplineFloat "{6A7AE25704798AE7}" {
    }
   }
   Axis09 InputProfileKey "{6A7AE25704798AE6}" {
    Transition CurveCubicSplineFloat "{6A7AE25704798AE0}" {
    }
   }
  }
  JoystickSettings JoystickSettings "{6A7AE25704798AEC}" {
  }
  GyroSettings GyroSettings "{6A7AE25704798AEB}" {
  }
 }
 MaterialSystemUserSettings MaterialSystemUserSettings {
 }
 PipelineUserSettings PipelineUserSettings {
 }
 PostprocessUserSettings PostprocessUserSettings {
 }
 ResourceManagerUserSettings ResourceManagerUserSettings {
 }
 TerrainGenMaterialSettings TerrainGenMaterialSettings {
 }
 UserInterfaceSettings UserInterfaceSettings {
  LanguageCode "en_us"
  SystemLanguageCode "en_us"
 }
 VideoUserSettings VideoUserSettings {
  WindowMode WINDOWED
  ScreenWidth 1920
  ScreenHeight 1080
  ResolutionScale 1
  WindowPosX 0
  WindowPosY 31
  Vsync 1
  Ratio3d 1
  Fsaa NONE
  RenderFormat STANDARD
  Gamma 0
  Contrast 0
  Brightness 0
  FsrEnabled 0
  FsrSharpening 0.75
  CasSharpening 0
 }
 WaterPoolMaterialSettings WaterPoolMaterialSettings {
 }
}