EngineUserSettings {
 AudioSettings AudioSettings {
 }
 DisplayUserSettings DisplayUserSettings {
  PPQuality PPEffectsSettings "{6A7AE1E201C30AC0}" {
  }
 }
 GameProjectUserSettings GameProjectUserSettings {
 }
 GraphicsQualitySettings GraphicsQualitySettings {
 }
 GrassMaterialSettings GrassMaterialSettings {
 }
 InputDeviceUserSettings InputDeviceUserSettings {
  GamepadProfile InputProfileGamepad "{6A7AE1E2048EC705}" {
   LeftThumbHorizontal InputProfileKey "{6A7AE1E2048EC70D}" {
    Transition CurveCubicSplineFloat "{6A7AE1E2048EC715}" {
    }
   }
   LeftThumbVertical InputProfileKey "{6A7AE1E2048EC710}" {
    Transition CurveCubicSplineFloat "{6A7AE1E2048EC712}" {
    }
   }
   RightThumbHorizontal InputProfileKey "{6A7AE1E2048EC71F}" {
    Transition CurveCubicSplineFloat "{6A7AE1E2048EC71E}" {
    }
   }
   RightThumbVertical InputProfileKey "{6A7AE1E2048EC718}" {
    Transition CurveCubicSplineFloat "{6A7AE1E2048EC71A}" {
    }
   }
   LeftTrigger InputProfileKey "{6A7AE1E2048EC764}" {
    Transition CurveCubicSplineFloat "{6A7AE1E2048EC777}" {
    }
   }
   RightTrigger InputProfileKey "{6A7AE1E2048EC771}" {
    Transition CurveCubicSplineFloat "{6A7AE1E2048EC772}" {
    }
   }
  }
  JoystickProfile InputProfileJoystick "{6A7AE1E2048EC77E}" {
   Axis00 InputProfileKey "{6A7AE1E2048EC77B}" {
    Transition CurveCubicSplineFloat "{6A7AE1E2048EC747}" {
    }
   }
   Axis01 InputProfileKey "{6A7AE1E2048EC741}" {
    Transition CurveCubicSplineFloat "{6A7AE1E2048EC743}" {
    }
   }
   Axis02 InputProfileKey "{6A7AE1E2048EC74D}" {
    Transition CurveCubicSplineFloat "{6A7AE1E2048EC74C}" {
    }
   }
   Axis03 InputProfileKey "{6A7AE1E2048EC74E}" {
    Transition CurveCubicSplineFloat "{6A7AE1E2048EC748}" {
    }
   }
   Axis04 InputProfileKey "{6A7AE1E2048EC74A}" {
    Transition CurveCubicSplineFloat "{6A7AE1E2048EC754}" {
    }
   }
   Axis05 InputProfileKey "{6A7AE1E2048EC756}" {
    Transition CurveCubicSplineFloat "{6A7AE1E2048EC751}" {
    }
   }
   Axis06 InputProfileKey "{6A7AE1E2048EC753}" {
    Transition CurveCubicSplineFloat "{6A7AE1E2048EC75D}" {
    }
   }
   Axis07 InputProfileKey "{6A7AE1E2048EC75C}" {
    Transition CurveCubicSplineFloat "{6A7AE1E2048ECE99}" {
    }
   }
   Axis08 InputProfileKey "{6A7AE1E2048ECE9B}" {
    Transition CurveCubicSplineFloat "{6A7AE1E2048ECE9C}" {
    }
   }
   Axis09 InputProfileKey "{6A7AE1E2048ECE9E}" {
    Transition CurveCubicSplineFloat "{6A7AE1E2048ECE9F}" {
    }
   }
  }
  JoystickSettings JoystickSettings "{6A7AE1E2048ECD62}" {
  }
  GyroSettings GyroSettings "{6A7AE1E2048ECD67}" {
  }
 }
 MaterialSystemUserSettings MaterialSystemUserSettings {
 }
 PipelineUserSettings PipelineUserSettings {
 }
 PostprocessUserSettings PostprocessUserSettings {
 }
 ResourceManagerUserSettings ResourceManagerUserSettings {
 }
 TerrainGenMaterialSettings TerrainGenMaterialSettings {
 }
 UserInterfaceSettings UserInterfaceSettings {
  LanguageCode "en_us"
  SystemLanguageCode "en_us"
 }
 VideoUserSettings VideoUserSettings {
  WindowPosX -760
  WindowPosY -180
 }
 WaterPoolMaterialSettings WaterPoolMaterialSettings {
 }
}