EngineUserSettings {
 AudioSettings AudioSettings {
 }
 DisplayUserSettings DisplayUserSettings {
  PPQuality PPEffectsSettings "{6A7AE14307573C88}" {
  }
 }
 GameProjectUserSettings GameProjectUserSettings {
 }
 GraphicsQualitySettings GraphicsQualitySettings {
 }
 GrassMaterialSettings GrassMaterialSettings {
 }
 InputDeviceUserSettings InputDeviceUserSettings {
  GamepadProfile InputProfileGamepad "{6A7AE1430478E4BB}" {
   LeftThumbHorizontal InputProfileKey "{6A7AE1430478E486}" {
    Transition CurveCubicSplineFloat "{6A7AE1430478E48F}" {
    }
   }
   LeftThumbVertical InputProfileKey "{6A7AE1430478E497}" {
    Transition CurveCubicSplineFloat "{6A7AE1430478E496}" {
    }
   }
   RightThumbHorizontal InputProfileKey "{6A7AE1430478E490}" {
    Transition CurveCubicSplineFloat "{6A7AE1430478E492}" {
    }
   }
   RightThumbVertical InputProfileKey "{6A7AE1430478E49C}" {
    Transition CurveCubicSplineFloat "{6A7AE1430478E49F}" {
    }
   }
   LeftTrigger InputProfileKey "{6A7AE1430478E49E}" {
    Transition CurveCubicSplineFloat "{6A7AE1430478E4E8}" {
    }
   }
   RightTrigger InputProfileKey "{6A7AE1430478E4EA}" {
    Transition CurveCubicSplineFloat "{6A7AE1430478E4F4}" {
    }
   }
  }
  JoystickProfile InputProfileJoystick "{6A7AE1430478E4F1}" {
   Axis00 InputProfileKey "{6A7AE1430478E4FD}" {
    Transition CurveCubicSplineFloat "{6A7AE1430478E4FE}" {
    }
   }
   Axis01 InputProfileKey "{6A7AE1430478E4FB}" {
    Transition CurveCubicSplineFloat "{6A7AE1430478E4C5}" {
    }
   }
   Axis02 InputProfileKey "{6A7AE1430478E4C7}" {
    Transition CurveCubicSplineFloat "{6A7AE1430478E4C1}" {
    }
   }
   Axis03 InputProfileKey "{6A7AE1430478E4C0}" {
    Transition CurveCubicSplineFloat "{6A7AE1430478E4C2}" {
    }
   }
   Axis04 InputProfileKey "{6A7AE1430478E4CF}" {
    Transition CurveCubicSplineFloat "{6A7AE1430478E4C9}" {
    }
   }
   Axis05 InputProfileKey "{6A7AE1430478E4C8}" {
    Transition CurveCubicSplineFloat "{6A7AE1430478E4CB}" {
    }
   }
   Axis06 InputProfileKey "{6A7AE1430478E4D5}" {
    Transition CurveCubicSplineFloat "{6A7AE1430478E4D4}" {
    }
   }
   Axis07 InputProfileKey "{6A7AE1430478E4D7}" {
    Transition CurveCubicSplineFloat "{6A7AE1430478E4D6}" {
    }
   }
   Axis08 InputProfileKey "{6A7AE1430478E4D1}" {
    Transition CurveCubicSplineFloat "{6A7AE1430478ED14}" {
    }
   }
   Axis09 InputProfileKey "{6A7AE1430478ED16}" {
    Transition CurveCubicSplineFloat "{6A7AE14304781FDC}" {
    }
   }
  }
  JoystickSettings JoystickSettings "{6A7AE14304781FD0}" {
  }
  GyroSettings GyroSettings "{6A7AE14304781FD4}" {
  }
 }
 MaterialSystemUserSettings MaterialSystemUserSettings {
 }
 PipelineUserSettings PipelineUserSettings {
 }
 PostprocessUserSettings PostprocessUserSettings {
 }
 ResourceManagerUserSettings ResourceManagerUserSettings {
 }
 TerrainGenMaterialSettings TerrainGenMaterialSettings {
 }
 UserInterfaceSettings UserInterfaceSettings {
  LanguageCode "en_us"
  SystemLanguageCode "en_us"
 }
 VideoUserSettings VideoUserSettings {
  WindowPosX -320
  WindowPosY -180
 }
 WaterPoolMaterialSettings WaterPoolMaterialSettings {
 }
}