EngineUserSettings {
 AudioSettings AudioSettings {
 }
 DisplayUserSettings DisplayUserSettings {
  PPQuality PPEffectsSettings "{6A7AE3180076918F}" {
  }
 }
 GameProjectUserSettings GameProjectUserSettings {
 }
 GraphicsQualitySettings GraphicsQualitySettings {
 }
 GrassMaterialSettings GrassMaterialSettings {
 }
 InputDeviceUserSettings InputDeviceUserSettings {
  GamepadProfile InputProfileGamepad "{6A7AE31804768065}" {
   LeftThumbHorizontal InputProfileKey "{6A7AE31804768062}" {
    Transition CurveCubicSplineFloat "{6A7AE31804768068}" {
    }
   }
   LeftThumbVertical InputProfileKey "{6A7AE31804768071}" {
    Transition CurveCubicSplineFloat "{6A7AE31804768073}" {
    }
   }
   RightThumbHorizontal InputProfileKey "{6A7AE3180476807F}" {
    Transition CurveCubicSplineFloat "{6A7AE31804768079}" {
    }
   }
   RightThumbVertical InputProfileKey "{6A7AE3180476807B}" {
    Transition CurveCubicSplineFloat "{6A7AE31804768045}" {
    }
   }
   LeftTrigger InputProfileKey "{6A7AE31804768044}" {
    Transition CurveCubicSplineFloat "{6A7AE31804768055}" {
    }
   }
   RightTrigger InputProfileKey "{6A7AE31804768057}" {
    Transition CurveCubicSplineFloat "{6A7AE31804768051}" {
    }
   }
  }
  JoystickProfile InputProfileJoystick "{6A7AE3180476805D}" {
   Axis00 InputProfileKey "{6A7AE3180476805E}" {
    Transition CurveCubicSplineFloat "{6A7AE3180476805A}" {
    }
   }
   Axis01 InputProfileKey "{6A7AE318047681A7}" {
    Transition CurveCubicSplineFloat "{6A7AE318047681A1}" {
    }
   }
   Axis02 InputProfileKey "{6A7AE318047681A0}" {
    Transition CurveCubicSplineFloat "{6A7AE318047681AD}" {
    }
   }
   Axis03 InputProfileKey "{6A7AE318047681AF}" {
    Transition CurveCubicSplineFloat "{6A7AE318047681A9}" {
    }
   }
   Axis04 InputProfileKey "{6A7AE318047681AB}" {
    Transition CurveCubicSplineFloat "{6A7AE318047681AA}" {
    }
   }
   Axis05 InputProfileKey "{6A7AE318047681B5}" {
    Transition CurveCubicSplineFloat "{6A7AE318047681B7}" {
    }
   }
   Axis06 InputProfileKey "{6A7AE318047681B0}" {
    Transition CurveCubicSplineFloat "{6A7AE318047681B3}" {
    }
   }
   Axis07 InputProfileKey "{6A7AE318047681B2}" {
    Transition CurveCubicSplineFloat "{6A7AE318047681BD}" {
    }
   }
   Axis08 InputProfileKey "{6A7AE318047681BF}" {
    Transition CurveCubicSplineFloat "{6A7AE3180476887A}" {
    }
   }
   Axis09 InputProfileKey "{6A7AE3180476887C}" {
    Transition CurveCubicSplineFloat "{6A7AE3180476887D}" {
    }
   }
  }
  JoystickSettings JoystickSettings "{6A7AE31804768840}" {
  }
  GyroSettings GyroSettings "{6A7AE31804768846}" {
  }
 }
 MaterialSystemUserSettings MaterialSystemUserSettings {
 }
 PipelineUserSettings PipelineUserSettings {
 }
 PostprocessUserSettings PostprocessUserSettings {
 }
 ResourceManagerUserSettings ResourceManagerUserSettings {
 }
 TerrainGenMaterialSettings TerrainGenMaterialSettings {
 }
 UserInterfaceSettings UserInterfaceSettings {
  LanguageCode "en_us"
  SystemLanguageCode "en_us"
 }
 VideoUserSettings VideoUserSettings {
  WindowMode WINDOWED
  ScreenWidth 1920
  ScreenHeight 1080
  ResolutionScale 1
  WindowPosX 0
  WindowPosY 31
  Vsync 1
  Ratio3d 1
  Fsaa NONE
  RenderFormat STANDARD
  Gamma 0
  Contrast 0
  Brightness 0
  FsrEnabled 0
  FsrSharpening 0.75
  CasSharpening 0
 }
 WaterPoolMaterialSettings WaterPoolMaterialSettings {
 }
}